[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pedro-organiza"
version = "0.1.0"
requires-python = ">=3.9"

[project.scripts]
pedro = "cli.pedro_cli:main"

[tool.setuptools]
packages = ["cli"]

